Revert "schedutil: Remove unused prev_cached_raw_freq"
This reverts commit 6897dba343367b2d89f9c06dead08d2310da1dca.

Now used again
../kernel/sched/cpufreq_schedutil.c:592:43: error: no member named 'prev_cached_raw_freq' in 'struct sugov_policy'

Signed-off-by: Yahya Wessam <yahyawessam2002@gmail.com>