Reapply "sysctl: Move sixty constant to common scope"
This reverts commit 1e5b98a40eed419c8853321b4c49d8724bdfa6dd.

Now it's used

../kernel/sysctl.c:1631:15: error: use of undeclared identifier 'sixty'
 1631 |                 .extra2         = &sixty,
      |                                    ^~~~~
../kernel/sysctl.c:1490:25: warning: tentative array definition assumed to have one element [-Wtentative-definition-array]
 1490 | static struct ctl_table vm_table[] = {
      |                         ^
1 warning and 1 error generated.
make[2]: *** [../scripts/Makefile.build:364: kernel/sysctl.o] Error 1

Signed-off-by: Yahya Wessam <yahyawessam2002@gmail.com>